#:schema node_modules/wrangler/config-schema.json
name = "cosmotmt"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "db"
database_id = "3dec4127-1d2a-4208-9589-3e6628e40f34"

[[r2_buckets]]
binding = "R2"
bucket_name = "storage"
